# Generated by Django 5.0.7 on 2026-06-11 23:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("skincare", "Skincare"),
                            ("makeup", "Makeup"),
                            ("fragrance", "Fragrance"),
                            ("wellness", "Wellness"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField()),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("badge", models.CharField(blank=True, max_length=50)),
                ("ingredients", models.TextField(blank=True)),
                ("is_new", models.BooleanField(default=False)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("in_stock", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
