# Generated by Django 5.2.11 on 2026-06-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
    ]
